//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef _CTEST_HH
#define _CTEST_HH

#include <map>
#include <iostream>
#include "aceSmartSoft.hh"
#include "smartQueryServerTaskTrigger_T.h"
#include "CTestCore.hh"

#include "CTestPortFactoryInterface.hh"
#include "CTestExtension.hh"

// forward declarations
class CTestPortFactoryInterface;
class CTestExtension;

// includes for CTestROSExtension

// includes for PlainOpcUaCTestExtension
// include plain OPC UA device clients
// include plain OPC UA status servers


// include communication objects
#include <CommObjectRecognitionObjects/CommColorDetection.hh>
#include <CommObjectRecognitionObjects/CommColorDetectionACE.hh>
#include <CommObjectRecognitionObjects/CommObjectRecognitionInformation.hh>
#include <CommObjectRecognitionObjects/CommObjectRecognitionInformationACE.hh>
#include <CommObjectRecognitionObjects/CommObjectRecognitionObjectProperties.hh>
#include <CommObjectRecognitionObjects/CommObjectRecognitionObjectPropertiesACE.hh>
#include <CommObjectRecognitionObjects/CommPoint2d.hh>
#include <CommObjectRecognitionObjects/CommPoint2dACE.hh>

// include tasks
#include "Test.hh"
// include UpcallManagers

// include input-handler
// include input-handler

// include handler
#include "CompHandler.hh"


#include "SmartStateChangeHandler.hh"

#define COMP CTest::instance()

class CTest : public CTestCore {
private:
	static CTest *_cTest;
	
	// constructor
	CTest();
	
	// copy-constructor
	CTest(const CTest& cc);
	
	// destructor
	~CTest() { };
	
	// load parameter from ini file
	void loadParameter(int argc, char* argv[]);
	
	// instantiate comp-handler
	CompHandler compHandler;
	
	// helper method that maps a string-name to an according TaskTriggerSubject
	Smart::TaskTriggerSubject* getInputTaskTriggerFromString(const std::string &client);
	
	// internal map storing the different port-creation factories (that internally map to specific middleware implementations)
	std::map<std::string, CTestPortFactoryInterface*> portFactoryRegistry;
	
	// internal map storing various extensions of this component class
	std::map<std::string, CTestExtension*> componentExtensionRegistry;
	
public:
	
	// define tasks
	Smart::TaskTriggerSubject* testTrigger;
	Test *test;
	
	// define input-ports
	
	// define request-ports
	Smart::IQueryClientPattern<CommObjectRecognitionObjects::CommColorDetection, CommObjectRecognitionObjects::CommPoint2d,SmartACE::QueryId> *colorQueryServiceReq;
	Smart::IQueryClientPattern<CommObjectRecognitionObjects::CommObjectRecognitionInformation, CommObjectRecognitionObjects::CommObjectRecognitionObjectProperties,SmartACE::QueryId> *objectRecognitionQueryServiceReq;
	
	// define input-handler
	
	// define output-ports
	
	// define answer-ports
	
	// define request-handlers
	
	// definitions of CTestROSExtension
	
	// definitions of PlainOpcUaCTestExtension
	
	
	// define default slave ports
	SmartACE::StateSlave *stateSlave;
	SmartStateChangeHandler *stateChangeHandler;
	SmartACE::WiringSlave *wiringSlave;
	
	
	/// this method is used to register different PortFactory classes (one for each supported middleware framework)
	void addPortFactory(const std::string &name, CTestPortFactoryInterface *portFactory);
	
	SmartACE::SmartComponent* getComponentImpl();
	
	/// this method is used to register different component-extension classes
	void addExtension(CTestExtension *extension);
	
	/// this method allows to access the registered component-extensions (automatically converting to the actuall implementation type)
	template <typename T>
	T* getExtension(const std::string &name) {
		auto it = componentExtensionRegistry.find(name);
		if(it != componentExtensionRegistry.end()) {
			return dynamic_cast<T*>(it->second);
		}
		return 0;
	}
	
	/// initialize component's internal members
	void init(int argc, char *argv[]);
	
	/// execute the component's infrastructure
	void run();
	
	/// clean-up component's resources
	void fini();
	
	/// call this method to set the overall component into the Alive state (i.e. component is then ready to operate)
	void setStartupFinished();
	
	/// connect all component's client ports
	Smart::StatusCode connectAndStartAllServices();
	
	/// start all assocuated Activities
	void startAllTasks();
	
	/// start all associated timers
	void startAllTimers();
	
	Smart::StatusCode connectColorQueryServiceReq(const std::string &serverName, const std::string &serviceName);
	Smart::StatusCode connectObjectRecognitionQueryServiceReq(const std::string &serverName, const std::string &serviceName);

	// return singleton instance
	static CTest* instance()
	{
		if(_cTest == 0) {
			_cTest = new CTest();
		}
		return _cTest;
	}
	
	static void deleteInstance() {
		if(_cTest != 0) {
			delete _cTest;
		}
	}
	
	// connections parameter
	struct connections_struct
	{
		// component struct
		struct component_struct
		{
			// the name of the component
			std::string name;
			std::string initialComponentMode;
			std::string defaultScheduler;
			bool useLogger;
		} component;
		
		//--- task parameter ---
		struct Test_struct {
			double minActFreq;
			double maxActFreq;
			std::string trigger;
			// only one of the following two params is 
			// actually used at run-time according 
			// to the system config model
			double periodicActFreq;
			// or
			std::string inPortRef;
			int prescale;
			// scheduling parameters
			std::string scheduler;
			int priority;
			int cpuAffinity;
		} test;
		
		//--- upcall parameter ---
		
		//--- server port parameter ---
	
		//--- client port parameter ---
		struct ColorQueryServiceReq_struct {
			bool initialConnect;
			std::string serverName;
			std::string serviceName;
			std::string wiringName;
			long interval;
			std::string roboticMiddleware;
		} colorQueryServiceReq;
		struct ObjectRecognitionQueryServiceReq_struct {
			bool initialConnect;
			std::string serverName;
			std::string serviceName;
			std::string wiringName;
			long interval;
			std::string roboticMiddleware;
		} objectRecognitionQueryServiceReq;
		
		// -- parameters for CTestROSExtension
		
		// -- parameters for PlainOpcUaCTestExtension
		
	} connections;
};
#endif
