//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "CTest.hh"
#include "smartTimedTaskTrigger.h"
//FIXME: implement logging
//#include "smartGlobalLogger.hh"

// the ace port-factory is used as a default port-mapping
#include "CTestAcePortFactory.hh"


// initialize static singleton pointer to zero
CTest* CTest::_cTest = 0;

// constructor
CTest::CTest()
{
	std::cout << "constructor of CTest\n";
	
	// set all pointer members to NULL
	colorQueryServiceReq = NULL;
	objectRecognitionQueryServiceReq = NULL;
	test = NULL;
	testTrigger = NULL;
	stateChangeHandler = NULL;
	stateSlave = NULL;
	wiringSlave = NULL;
	
	// set default ini parameter values
	connections.component.name = "CTest";
	connections.component.initialComponentMode = "Neutral";
	connections.component.defaultScheduler = "DEFAULT";
	connections.component.useLogger = false;
	
	connections.colorQueryServiceReq.initialConnect = false;
	connections.colorQueryServiceReq.wiringName = "ColorQueryServiceReq";
	connections.colorQueryServiceReq.serverName = "unknown";
	connections.colorQueryServiceReq.serviceName = "unknown";
	connections.colorQueryServiceReq.interval = 1;
	connections.colorQueryServiceReq.roboticMiddleware = "ACE_SmartSoft";
	connections.objectRecognitionQueryServiceReq.initialConnect = false;
	connections.objectRecognitionQueryServiceReq.wiringName = "ObjectRecognitionQueryServiceReq";
	connections.objectRecognitionQueryServiceReq.serverName = "unknown";
	connections.objectRecognitionQueryServiceReq.serviceName = "unknown";
	connections.objectRecognitionQueryServiceReq.interval = 1;
	connections.objectRecognitionQueryServiceReq.roboticMiddleware = "ACE_SmartSoft";
	connections.test.minActFreq = 0.0;
	connections.test.maxActFreq = 0.0;
	// scheduling default parameters
	connections.test.scheduler = "DEFAULT";
	connections.test.priority = -1;
	connections.test.cpuAffinity = -1;
	
	// initialize members of CTestROSExtension
	
	// initialize members of PlainOpcUaCTestExtension
	
}

void CTest::addPortFactory(const std::string &name, CTestPortFactoryInterface *portFactory)
{
	portFactoryRegistry[name] = portFactory;
}

void CTest::addExtension(CTestExtension *extension)
{
	componentExtensionRegistry[extension->getName()] = extension;
}

SmartACE::SmartComponent* CTest::getComponentImpl()
{
	return dynamic_cast<CTestAcePortFactory*>(portFactoryRegistry["ACE_SmartSoft"])->getComponentImpl();
}

/**
 * Notify the component that setup/initialization is finished.
 * You may call this function from anywhere in the component.
 *
 * Set component's internal lifecycle state automaton (if any) into 
 * Alive mode (from here on the component is ready to provide its services)
 */
void CTest::setStartupFinished() {
	stateSlave->setWaitState("Alive");
	std::cout << "ComponentDefinition initialization/startup finished." << std::endl;
}


Smart::StatusCode CTest::connectColorQueryServiceReq(const std::string &serverName, const std::string &serviceName) {
	Smart::StatusCode status;
	
	if(connections.colorQueryServiceReq.initialConnect == false) {
		return Smart::SMART_OK;
	}
	std::cout << "connecting to: " << serverName << "; " << serviceName << std::endl;
	status = colorQueryServiceReq->connect(serverName, serviceName);
	while(status != Smart::SMART_OK)
	{
		ACE_OS::sleep(ACE_Time_Value(0,500000));
		status = COMP->colorQueryServiceReq->connect(serverName, serviceName);
	}
	std::cout << "connected.\n";
	return status;
}
Smart::StatusCode CTest::connectObjectRecognitionQueryServiceReq(const std::string &serverName, const std::string &serviceName) {
	Smart::StatusCode status;
	
	if(connections.objectRecognitionQueryServiceReq.initialConnect == false) {
		return Smart::SMART_OK;
	}
	std::cout << "connecting to: " << serverName << "; " << serviceName << std::endl;
	status = objectRecognitionQueryServiceReq->connect(serverName, serviceName);
	while(status != Smart::SMART_OK)
	{
		ACE_OS::sleep(ACE_Time_Value(0,500000));
		status = COMP->objectRecognitionQueryServiceReq->connect(serverName, serviceName);
	}
	std::cout << "connected.\n";
	return status;
}


/**
 * First connect ALL client ports contained in this component, then start all services:
 * activate state, push, etc...
 */
Smart::StatusCode CTest::connectAndStartAllServices() {
	Smart::StatusCode status = Smart::SMART_OK;
	
	status = connectColorQueryServiceReq(connections.colorQueryServiceReq.serverName, connections.colorQueryServiceReq.serviceName);
	if(status != Smart::SMART_OK) return status;
	status = connectObjectRecognitionQueryServiceReq(connections.objectRecognitionQueryServiceReq.serverName, connections.objectRecognitionQueryServiceReq.serviceName);
	if(status != Smart::SMART_OK) return status;
	return status;
}

/**
 * Start all tasks contained in this component.
 */
void CTest::startAllTasks() {
	// start task Test
	if(connections.test.scheduler != "DEFAULT") {
		ACE_Sched_Params test_SchedParams(ACE_SCHED_OTHER, ACE_THR_PRI_OTHER_DEF);
		if(connections.test.scheduler == "FIFO") {
			test_SchedParams.policy(ACE_SCHED_FIFO);
			test_SchedParams.priority(ACE_THR_PRI_FIFO_MIN);
		} else if(connections.test.scheduler == "RR") {
			test_SchedParams.policy(ACE_SCHED_RR);
			test_SchedParams.priority(ACE_THR_PRI_RR_MIN);
		}
		test->start(test_SchedParams, connections.test.cpuAffinity);
	} else {
		test->start();
	}
}

/**
 * Start all timers contained in this component
 */
void CTest::startAllTimers() {
}


Smart::TaskTriggerSubject* CTest::getInputTaskTriggerFromString(const std::string &client)
{
	
	return NULL;
}


void CTest::init(int argc, char *argv[])
{
	try {
		Smart::StatusCode status;
		
		// load initial parameters from ini-file (if found)
		loadParameter(argc, argv);
		
		
		// initializations of CTestROSExtension
		
		// initializations of PlainOpcUaCTestExtension
		
		
		// initialize all registered port-factories
		for(auto portFactory = portFactoryRegistry.begin(); portFactory != portFactoryRegistry.end(); portFactory++) 
		{
			portFactory->second->initialize(this, argc, argv);
		}
		
		// initialize all registered component-extensions
		for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
		{
			extension->second->initialize(this, argc, argv);
		}
		
		CTestPortFactoryInterface *acePortFactory = portFactoryRegistry["ACE_SmartSoft"];
		if(acePortFactory == 0) {
			std::cerr << "ERROR: acePortFactory NOT instantiated -> exit(-1)" << std::endl;
			exit(-1);
		}
		
		// this pointer is used for backwards compatibility (deprecated: should be removed as soon as all patterns, including coordination, are moved to port-factory)
		SmartACE::SmartComponent *component = dynamic_cast<CTestAcePortFactory*>(acePortFactory)->getComponentImpl();
		
		std::cout << "ComponentDefinition CTest is named " << connections.component.name << std::endl;
		
		if(connections.component.useLogger == true) {
			//FIXME: use logging
			//Smart::LOGGER->openLogFileInFolder("data/"+connections.component.name);
			//Smart::LOGGER->startLogging();
		}

		// create event-test handlers (if needed)
		
		// create server ports
		// TODO: set minCycleTime from Ini-file
		
		// create client ports
		colorQueryServiceReq = portFactoryRegistry[connections.colorQueryServiceReq.roboticMiddleware]->createColorQueryServiceReq();
		objectRecognitionQueryServiceReq = portFactoryRegistry[connections.objectRecognitionQueryServiceReq.roboticMiddleware]->createObjectRecognitionQueryServiceReq();
		
		// create InputTaskTriggers and UpcallManagers
		
		// create input-handler
		
		// create request-handlers
		
		// create state pattern
		stateChangeHandler = new SmartStateChangeHandler();
		stateSlave = new SmartACE::StateSlave(component, stateChangeHandler);
		status = stateSlave->setUpInitialState(connections.component.initialComponentMode);
		if (status != Smart::SMART_OK) std::cerr << status << "; failed setting initial ComponentMode: " << connections.component.initialComponentMode << std::endl;
		// activate state slave
		status = stateSlave->activate();
		if(status != Smart::SMART_OK) std::cerr << "ERROR: activate state" << std::endl;
		
		wiringSlave = new SmartACE::WiringSlave(component);
		// add client port to wiring slave
		if(connections.colorQueryServiceReq.roboticMiddleware == "ACE_SmartSoft") {
			//FIXME: this must also work with other implementations
			dynamic_cast<SmartACE::QueryClient<CommObjectRecognitionObjects::CommColorDetection, CommObjectRecognitionObjects::CommPoint2d>*>(colorQueryServiceReq)->add(wiringSlave, connections.colorQueryServiceReq.wiringName);
		}
		if(connections.objectRecognitionQueryServiceReq.roboticMiddleware == "ACE_SmartSoft") {
			//FIXME: this must also work with other implementations
			dynamic_cast<SmartACE::QueryClient<CommObjectRecognitionObjects::CommObjectRecognitionInformation, CommObjectRecognitionObjects::CommObjectRecognitionObjectProperties>*>(objectRecognitionQueryServiceReq)->add(wiringSlave, connections.objectRecognitionQueryServiceReq.wiringName);
		}
		
		
		
		// create Task Test
		test = new Test(component);
		// configure input-links
		// configure task-trigger (if task is configurable)
		if(connections.test.trigger == "PeriodicTimer") {
			// create PeriodicTimerTrigger
			int microseconds = 1000*1000 / connections.test.periodicActFreq;
			if(microseconds > 0) {
				Smart::TimedTaskTrigger *triggerPtr = new Smart::TimedTaskTrigger();
				triggerPtr->attach(test);
				component->getTimerManager()->scheduleTimer(triggerPtr, (void *) 0, std::chrono::microseconds(microseconds), std::chrono::microseconds(microseconds));
				// store trigger in class member
				testTrigger = triggerPtr;
			} else {
				std::cerr << "ERROR: could not set-up Timer with cycle-time " << microseconds << " as activation source for Task Test" << std::endl;
			}
		} else if(connections.test.trigger == "DataTriggered") {
			testTrigger = getInputTaskTriggerFromString(connections.test.inPortRef);
			if(testTrigger != NULL) {
				testTrigger->attach(test, connections.test.prescale);
			} else {
				std::cerr << "ERROR: could not set-up InPort " << connections.test.inPortRef << " as activation source for Task Test" << std::endl;
			}
		} 
		
		
		// link observers with subjects
	} catch (const std::exception &ex) {
		std::cerr << "Uncaught std exception" << ex.what() << std::endl;
	} catch (...) {
		std::cerr << "Uncaught exception" << std::endl;
	}
}

// run the component
void CTest::run()
{
	stateSlave->acquire("init");
	// startup all registered port-factories
	for(auto portFactory = portFactoryRegistry.begin(); portFactory != portFactoryRegistry.end(); portFactory++) 
	{
		portFactory->second->onStartup();
	}
	
	// startup all registered component-extensions
	for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
	{
		extension->second->onStartup();
	}
	stateSlave->release("init");
	
	// do not call this handler within the init state (see above) as this handler internally calls setStartupFinished() (this should be fixed in future)
	compHandler.onStartup();
	
	// this call blocks until the component is commanded to shutdown
	stateSlave->acquire("shutdown");
	
	// shutdown all registered component-extensions
	for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
	{
		extension->second->onShutdown();
	}
	
	// shutdown all registered port-factories
	for(auto portFactory = portFactoryRegistry.begin(); portFactory != portFactoryRegistry.end(); portFactory++) 
	{
		portFactory->second->onShutdown();
	}
	
	if(connections.component.useLogger == true) {
		//FIXME: use logging
		//Smart::LOGGER->stopLogging();
	}
	
	compHandler.onShutdown();
	
	stateSlave->release("shutdown");
}

// clean-up component's resources
void CTest::fini()
{
	// unlink all observers
	
	// destroy all task instances
	// unlink all UpcallManagers
	// unlink the TaskTrigger
	if(testTrigger != NULL){
		testTrigger->detach(test);
		delete test;
	}

	// destroy all input-handler

	// destroy InputTaskTriggers and UpcallManagers

	// destroy client ports
	delete colorQueryServiceReq;
	delete objectRecognitionQueryServiceReq;

	// destroy server ports
	// destroy event-test handlers (if needed)
	
	// destroy request-handlers
	
	delete stateSlave;
	// destroy state-change-handler
	delete stateChangeHandler;
	
	// destroy all master/slave ports
	delete wiringSlave;
	

	// destroy all registered component-extensions
	for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
	{
		extension->second->destroy();
	}

	// destroy all registered port-factories
	for(auto portFactory = portFactoryRegistry.begin(); portFactory != portFactoryRegistry.end(); portFactory++) 
	{
		portFactory->second->destroy();
	}
	
	// destruction of CTestROSExtension
	
	// destruction of PlainOpcUaCTestExtension
	
}

void CTest::loadParameter(int argc, char *argv[])
{
	/*
	 Parameters can be specified via command line --filename=<filename> or -f <filename>

	 With this parameter present:
	   - The component will look for the file in the current working directory,
	     a path relative to the current directory or any absolute path
	   - The component will use the default values if the file cannot be found

	 With this parameter absent:
	   - <Name of Component>.ini will be read from current working directory, if found there
	   - $SMART_ROOT/etc/<Name of Component>.ini will be read otherwise
	   - Default values will be used if neither found in working directory or /etc
	 */
	SmartACE::SmartIniParameter parameter;
	std::ifstream parameterfile;
	bool parameterFileFound = false;

	// load parameters
	try
	{
		// if paramfile is given as argument
		if(parameter.tryAddFileFromArgs(argc,argv,"filename", 'f'))
		{
			parameterFileFound = true;
			std::cout << "parameter file is loaded from an argv argument \n";
		} else if(parameter.searchFile("CTest.ini", parameterfile)) {
			parameterFileFound = true;
			std::cout << "load CTest.ini parameter file\n";
			parameter.addFile(parameterfile);
		} else {
			std::cout << "WARNING: CTest.ini parameter file not found! (using default values or command line arguments)\n";
		}
		
		// add command line arguments to allow overwriting of parameters
		// from file
		parameter.addCommandLineArgs(argc,argv,"component");
		
		// initialize the naming service using the command line parameters parsed in the
		// SmartIniParameter class. The naming service parameters are expected to be in
		// the "component" parameter group.
		SmartACE::NAMING::instance()->checkForHelpArg(argc,argv);
		if(parameterFileFound) 
		{
			if(SmartACE::NAMING::instance()->init(parameter.getAllParametersFromGroup("component")) != 0) {
				// initialization of naming service failed
				throw std::logic_error( "<NamingService> Service initialization failed!\nPossible causes could be:\n-> Erroneous configuration.\n-> Naming service not reachable.\n" );
			}
		} else {
			if(SmartACE::NAMING::instance()->init(argc, argv) != 0) {
				// initialization of naming service failed
				throw std::logic_error( "<NamingService> Service initialization failed!\nPossible causes could be:\n-> Erroneous configuration.\n-> Naming service not reachable.\n" );
			}
		}
			
		// print all known parameters
		// parameter.print();
		
		//--- server port // client port // other parameter ---
		// load parameter
		parameter.getString("component", "name", connections.component.name);
		parameter.getString("component", "initialComponentMode", connections.component.initialComponentMode);
		if(parameter.checkIfParameterExists("component", "defaultScheduler")) {
			parameter.getString("component", "defaultScheduler", connections.component.defaultScheduler);
		}
		if(parameter.checkIfParameterExists("component", "useLogger")) {
			parameter.getBoolean("component", "useLogger", connections.component.useLogger);
		}
		
		// load parameters for client ColorQueryServiceReq
		parameter.getBoolean("ColorQueryServiceReq", "initialConnect", connections.colorQueryServiceReq.initialConnect);
		parameter.getString("ColorQueryServiceReq", "serviceName", connections.colorQueryServiceReq.serviceName);
		parameter.getString("ColorQueryServiceReq", "serverName", connections.colorQueryServiceReq.serverName);
		parameter.getString("ColorQueryServiceReq", "wiringName", connections.colorQueryServiceReq.wiringName);
		if(parameter.checkIfParameterExists("ColorQueryServiceReq", "roboticMiddleware")) {
			parameter.getString("ColorQueryServiceReq", "roboticMiddleware", connections.colorQueryServiceReq.roboticMiddleware);
		}
		// load parameters for client ObjectRecognitionQueryServiceReq
		parameter.getBoolean("ObjectRecognitionQueryServiceReq", "initialConnect", connections.objectRecognitionQueryServiceReq.initialConnect);
		parameter.getString("ObjectRecognitionQueryServiceReq", "serviceName", connections.objectRecognitionQueryServiceReq.serviceName);
		parameter.getString("ObjectRecognitionQueryServiceReq", "serverName", connections.objectRecognitionQueryServiceReq.serverName);
		parameter.getString("ObjectRecognitionQueryServiceReq", "wiringName", connections.objectRecognitionQueryServiceReq.wiringName);
		if(parameter.checkIfParameterExists("ObjectRecognitionQueryServiceReq", "roboticMiddleware")) {
			parameter.getString("ObjectRecognitionQueryServiceReq", "roboticMiddleware", connections.objectRecognitionQueryServiceReq.roboticMiddleware);
		}
		
		
		// load parameters for task Test
		parameter.getDouble("Test", "minActFreqHz", connections.test.minActFreq);
		parameter.getDouble("Test", "maxActFreqHz", connections.test.maxActFreq);
		parameter.getString("Test", "triggerType", connections.test.trigger);
		if(connections.test.trigger == "PeriodicTimer") {
			parameter.getDouble("Test", "periodicActFreqHz", connections.test.periodicActFreq);
		} else if(connections.test.trigger == "DataTriggered") {
			parameter.getString("Test", "inPortRef", connections.test.inPortRef);
			parameter.getInteger("Test", "prescale", connections.test.prescale);
		}
		if(parameter.checkIfParameterExists("Test", "scheduler")) {
			parameter.getString("Test", "scheduler", connections.test.scheduler);
		}
		if(parameter.checkIfParameterExists("Test", "priority")) {
			parameter.getInteger("Test", "priority", connections.test.priority);
		}
		if(parameter.checkIfParameterExists("Test", "cpuAffinity")) {
			parameter.getInteger("Test", "cpuAffinity", connections.test.cpuAffinity);
		}
		
		// load parameters for CTestROSExtension
		
		// load parameters for PlainOpcUaCTestExtension
		
		
		// load parameters for all registered component-extensions
		for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
		{
			extension->second->loadParameters(parameter);
		}
		
	
	} catch (const SmartACE::IniParameterError & e) {
		std::cerr << e.what() << std::endl;
	} catch (const std::exception &ex) {
		std::cerr << "Uncaught std::exception: " << ex.what() << std::endl;
	} catch (...) {
		std::cerr << "Uncaught exception" << std::endl;
	}
}
