//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------

#ifndef CTEST_ACE_PORTFACTORY_HH_
#define CTEST_ACE_PORTFACTORY_HH_

// include ACE/SmartSoft component implementation
#include "CTestImpl.hh"

// include the main component-definition class
#include "CTestPortFactoryInterface.hh"

class CTestAcePortFactory: public CTestPortFactoryInterface
{
private:
	CTestImpl *componentImpl;
public:
	CTestAcePortFactory();
	virtual ~CTestAcePortFactory();

	virtual void initialize(CTest *component, int argc, char* argv[]) override;
	virtual int onStartup() override;

	virtual Smart::IQueryClientPattern<CommObjectRecognitionObjects::CommColorDetection, CommObjectRecognitionObjects::CommPoint2d,SmartACE::QueryId> * createColorQueryServiceReq() override;
	virtual Smart::IQueryClientPattern<CommObjectRecognitionObjects::CommObjectRecognitionInformation, CommObjectRecognitionObjects::CommObjectRecognitionObjectProperties,SmartACE::QueryId> * createObjectRecognitionQueryServiceReq() override;
	
	
	// get a pointer to the internal component implementation
	SmartACE::SmartComponent* getComponentImpl();

	virtual int onShutdown(const std::chrono::steady_clock::duration &timeoutTime=std::chrono::seconds(2)) override;
	virtual void destroy() override;
};

#endif /* CTEST_ACE_PORTFACTORY_HH_ */
