//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef _CAPTURE_HH
#define _CAPTURE_HH

#include "CaptureCore.hh"
#include <opencv2/opencv.hpp>

using namespace cv;

class Capture  : public CaptureCore
{
private:
	cv::Mat image_example;
public:
	Capture(SmartACE::SmartComponent *comp);
	cv::Mat Segmentation(cv::Mat img);
	virtual ~Capture();
	
	virtual int on_entry();
	virtual int on_execute();
	virtual int on_exit();
};

#endif
