//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#include "ObjectSegmentationService.hh"
#include "ColorSegmentation.hh"

ObjectSegmentationService::ObjectSegmentationService(Smart::IQueryServerPattern<CommObjectRecognitionObjects::CommObjectRecognitionId, CommObjectRecognitionObjects::CommObjectRecognitionObjectProperties, SmartACE::QueryId>* server)
:	ObjectSegmentationServiceCore(server)
{
	
}

ObjectSegmentationService::~ObjectSegmentationService()
{
	
}


void ObjectSegmentationService::handleQuery(const SmartACE::QueryId &id, const CommObjectRecognitionObjects::CommObjectRecognitionId& request) 
{
	CommObjectRecognitionObjects::CommObjectRecognitionObjectProperties answer;
	
	// implement your query handling logic here and fill in the answer object
	
	this->server->answer(id, answer);
}
